sudo: false
language: rust
rust:
  - nightly
cache: cargo

before_script:
  - |
      cargo install cargo-travis &&
      export PATH=$HOME/.cargo/bin:$PATH

# the main build
script:
  - |
      cargo build &&
      cargo test &&
      cargo doc

after_success:
# measure code coverage and upload to coveralls.io
  - cargo coveralls
