language: rust
sudo: required
cache: cargo
dist: trusty
rust:
  - stable
  - beta
  - nightly
addons:
    apt:
        packages:
            - libssl-dev

script:
  - cargo build
  - cargo test
  - cargo doc

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install cargo-tarpaulin
    cargo tarpaulin --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi
