[package]
name = "fluent-locale"
description = """
A library for language and locale negotiation.
"""
version = "0.6.0"
authors = ["Zibi Braniecki <gandalf@mozilla.com>"]
homepage = "http://projectfluent.org/"
license = "Apache-2.0"
repository = "https://github.com/projectfluent/fluent-locale-rs"
readme = "README.md"
categories = ["internationalization", "localization"]
edition = "2018"

[badges]
travis-ci = { repository = "projectfluent/fluent-locale-rs" }
coveralls = { repository = "projectfluent/fluent-locale-rs", branch = "master", service = "github" }

maintenance = { status = "actively-developed" }

[dependencies]
unic-langid = { git = "https://github.com/zbraniecki/unic-locale", branch = "master" }

[dev-dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
unic-locale = { git = "https://github.com/zbraniecki/unic-locale", branch = "master" }