[package]
name = "fluent-locale"
description = """
A library for parsing, serializing, manipulating and negotiating locales and language tags.
"""
version = "0.2.0"
authors = ["Zibi Braniecki <gandalf@mozilla.com>"]
homepage = "http://projectfluent.io/"
license = "Apache-2.0"
repository = "https://github.com/zbraniecki/fluent-locale-rs"
readme = "README.md"
categories = ["internationalization", "localization"]

[dependencies]

[dev-dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
